###############################################################
# Program:
#     Checkpoint 06a, Makefiles
#     Brother Walker, CS165
# Author:
#     Glaucio Oliveira
# Summary:
#     Summaries are not necessary for checkpoint assignments.
###############################################################


# Insert your rule for a.out here:


# Insert your rule for robot.o here:


# Insert your rule for point.o here:


# Insert your rule for check06a.o here:
