###############################################################
# Program:
#     Assignment 04, Product inventory
#     Brother Walker, CS165
# Author:
#     Glaucio Oliveira
# Summary:
#     ECOMMERCE PRODUCT INVENTORY 
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp assign04.cpp
	g++ product.cpp assign04.cpp

